# Generated by Django 5.2.5 on 2025-09-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='numero_licencia',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agente',
            name='puntaje',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
