# Generated by Django 5.2.5 on 2025-09-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_agente_numero_licencia_alter_agente_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
