# Generated by Django 5.2.6 on 2025-09-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('NombreUsuario', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('Telefono', models.CharField(blank=True, max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
